{
  "openapi": "3.0.3",
  "info": {
    "title": "Bingle_Shop API",
    "description": "Documentation of Bingle_Shop ecommerce's endpoints and how to use them",
    "version": "1.0.11"
  },
  "servers": [
    {
      "url": "http://localhost:1990"
    }
  ],
  "tags": [
    {
      "name": "users",
      "description": "User's endpoints",
      "externalDocs": {
        "description": "Find out more",
        "url": "editor.swagger.io"
      }
    },
    {
      "name": "items",
      "description": "Item's endpoints",
      "externalDocs": {
        "description": "Find out more",
        "url": "editor.swagger.io"
      }
    },
    {
      "name": "orders",
      "description": "Order's endpoints",
      "externalDocs": {
        "description": "Find out more",
        "url": "editor.swagger.io"
      }
    }
  ],
  "paths": {
    "/register/v1": {
      "post": {
        "tags": [
          "users"
        ],
        "summary": "Register user",
        "description": "This can only be done by the logged in user.",
        "operationId": "createUser",
        "requestBody": {
          "description": "Register user object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/registerUser"
              }
            },
            "application/x-www-form-urlencoded": {
              "schema": {
                "$ref": "#/components/schemas/registerUser"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": true,
                  "message": "Cek Your Email For Verify!!",
                  "status_code": 200,
                  "data": {
                    "name": "John",
                    "email": "john@email.com"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Input Email & Password || Invalid email format",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": false,
                  "message": "Input Email & Password || Invalid email format",
                  "status_code": 400,
                  "data": null
                }
              }
            }
          },
          "409": {
            "description": "Email Already Exist!",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": false,
                  "message": "Email Already Exist!",
                  "status_code": 409,
                  "data": null
                }
              }
            }
          }
        }
      }
    },
    "/login/v1": {
      "post": {
        "tags": [
          "users"
        ],
        "summary": "Login user",
        "description": "This can only be done by the logged in user.",
        "operationId": "loginUser",
        "requestBody": {
          "description": "Login user object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/loginUser"
              }
            },
            "application/x-www-form-urlencoded": {
              "schema": {
                "$ref": "#/components/schemas/loginUser"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Login Success!",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": true,
                  "message": "Login Succcess! üëè",
                  "status_code": 200,
                  "data": {
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6IlJhcmEiLCJlbWFpbCI6ImtlcnVwdWtsYWRhN0BnbWFpbC5jb20iLCJpc19hZG1pbiI6ZmFsc2UsImlhdCI6MTcwOTg5OTg4OSwiZXhwIjoxNzA5OTg2Mjg5fQ.oU1wz3lMwacGf6nKAFHlbP7AndiqzIjAopGHDPGrfzo"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Please Verify Your Email || Incorrect Password!",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": false,
                  "message": "Please Verify Your Email || Incorrect Password!",
                  "status_code": 400,
                  "data": null
                }
              }
            }
          },
          "401": {
            "description": "Incorrect Password!",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": false,
                  "message": "Incorrect Password!",
                  "status_code": 401,
                  "data": null
                }
              }
            }
          },
          "404": {
            "description": "Email Not Found!",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": false,
                  "message": "Email Not Found!",
                  "status_code": 404,
                  "data": null
                }
              }
            }
          }
        }
      }
    },
    "/updateAdmin/v1": {
      "put": {
        "tags": [
          "users"
        ],
        "summary": "Update Order",
        "description": "Update admin status",
        "operationId": "getting the user from JWT session  and updating admin status to true",
        "security": [
          {
            "JWTAuthorization": []
          }
        ],
        "responses": {
          "200": {
            "description": "ID is now an admin. || ID is already an admin.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": true,
                  "message": "ID is now an admin. || ID is already an admin.",
                  "status_code": 200,
                  "data": {
                    "is_admin": true
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "ID is not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": false,
                  "message": "ID is not found!",
                  "status_code": 404,
                  "data": null
                }
              }
            }
          }
        }
      }
    },
    "/all/v1": {
      "get": {
        "tags": [
          "users"
        ],
        "summary": "Get Item",
        "description": "Show all items",
        "operationId": "getAll",
        "security": [
          {
            "JWTAuthorization": []
          }
        ],
        "responses": {
          "200": {
            "description": "Get All Data Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/users"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/verify/v1": {
      "get": {
        "tags": [
          "users"
        ],
        "summary": "Get user by id",
        "description": "Find User By id",
        "operationId": "getOne",
        "parameters": [
          {
            "name": "token",
            "in": "query",
            "description": "Tags to filter by",
            "required": true,
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Email verified",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": true,
                  "message": "Email Veerified üéâüéâüéâ",
                  "status_code": 200,
                  "data": {
                    "id": 7,
                    "verify": true,
                    "token_verify": null
                  }
                }
              }
            }
          },
          "404": {
            "description": "Token Not Valid",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": false,
                  "message": "Token Not Valid üëé",
                  "status_code": 404,
                  "data": null
                }
              }
            }
          }
        }
      }
    },
    "/user/v1/{id}": {
      "get": {
        "tags": [
          "users"
        ],
        "summary": "Finds User by Id",
        "description": "Finds User by Id",
        "security": [
          {
            "JWTAuthorization": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Get All Data Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/findUsers"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "User Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/userNotFound"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/update/v1/": {
      "put": {
        "tags": [
          "users"
        ],
        "summary": "Update an existing account",
        "description": "Update an existing account by Id",
        "operationId": "update",
        "security": [
          {
            "JWTAuthorization": []
          }
        ],
        "requestBody": {
          "description": "Update an existing account in the database",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/updateUser"
              }
            },
            "application/x-www-form-urlencoded": {
              "schema": {
                "$ref": "#/components/schemas/updateUser"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "USER UPDATE SUCCESS.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": true,
                  "message": "USER UPDATE SUCCESS.",
                  "status_code": 200,
                  "data": {
                    "id": "8,",
                    "first_name": "Check",
                    "last_name": "321",
                    "email": "cek321@gmail.com",
                    "password": "$2b$10$HbQ9MCMlrlRP68pGkkLhAe6LAKayuV.hpSMPZj2VRB/dXhBkNcVQC",
                    "phone": "081111",
                    "created_at": "2024-03-19 14:40:44",
                    "updated_at": "2024-03-19 14:46:5",
                    "token_verify": null,
                    "verify": true,
                    "is_admin": false
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "USER NOT FOUND!",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": false,
                  "message": "USER NOT FOUND!",
                  "status_code": 404,
                  "data": null
                }
              }
            }
          }
        }
      }
    },
    "/updateDetail/v1/": {
      "put": {
        "tags": [
          "users"
        ],
        "summary": "Update detail account",
        "description": "Update detail account",
        "operationId": "UpdateDetail",
        "security": [
          {
            "JWTAuthorization": []
          }
        ],
        "requestBody": {
          "description": "Update detail account",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/userDetail"
              }
            },
            "application/x-www-form-urlencoded": {
              "schema": {
                "$ref": "#/components/schemas/userDetail"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "USER DETAILS UPDATE SUCCESS.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": true,
                  "message": "USER DETAILS UPDATE SUCCESS.",
                  "status_code": 200,
                  "data": {
                    "id": "8,",
                    "user_id": "8,",
                    "address": "Sabang 2 street",
                    "city": "Jakarta city",
                    "postal_code": "40222",
                    "country_code": "Indonesia",
                    "created_at": "2024-03-19 14:40:44",
                    "updated_at": "2024-03-19 14:54:22"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "USER NOT FOUND!",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": false,
                  "message": "USER NOT FOUND!",
                  "status_code": 404,
                  "data": null
                }
              }
            }
          }
        }
      }
    },
    "/delete/v1/:{id}": {
      "delete": {
        "tags": [
          "users"
        ],
        "summary": "delete account",
        "description": "delete account",
        "operationId": "deleted",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "DELETE SUCCESS!",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": true,
                  "message": "DELETE SUCCESS!",
                  "status_code": 200,
                  "data": null
                }
              }
            }
          },
          "404": {
            "description": "USER NOT FOUND or ALREADY DELETED.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": false,
                  "message": "USER NOT FOUND or ALREADY DELETED.",
                  "status_code": 404,
                  "data": null
                }
              }
            }
          }
        }
      }
    },
    "/create/item/v1": {
      "post": {
        "tags": [
          "items"
        ],
        "summary": "Add a new item",
        "description": "Add a item",
        "operationId": "creating item",
        "security": [
          {
            "JWTAuthorization": []
          }
        ],
        "requestBody": {
          "description": "Input item",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Item"
              }
            },
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/ItemFormData"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "CREATE ITEM SUCCESS!",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": true,
                  "message": "CREATE ITEM SUCCESS!",
                  "status_code": 201,
                  "data": {
                    "id": "16,",
                    "item_name": "Test Item",
                    "item_price": 100,
                    "item_image": "http://res.cloudinary.com/dbdfdzrlu/image/upload/v1710836552/y8hsjy3olugzzqttjxtk.png",
                    "item_stock": 10,
                    "item_description": "Test description",
                    "created_at": "2024-03-19 15:22:30",
                    "updated_at": "2024-03-19 15:22:30"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid input",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": false,
                  "message": "Input Name and Price üôè || Please Upload Item Image",
                  "status_code": 404,
                  "data": null
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/update/item/v1/:{id}": {
      "put": {
        "tags": [
          "items"
        ],
        "summary": "Updating item",
        "description": "updating item",
        "operationId": "updating item",
        "security": [
          {
            "JWTAuthorization": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "description": "Input item",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/updateItem"
              }
            },
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/ItemFormData"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "ITEM UPDATE SUCCESS!",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": true,
                  "message": "ITEM UPDATE SUCCESS!",
                  "status_code": 201,
                  "data": {
                    "id": 16,
                    "item_name": "Motor Yamaha N-Max",
                    "item_price": 32000000,
                    "item_image": "https://www.yamaha-motor.co.id/uploads/products/new_product_model_image/202202151255313503V70891.png",
                    "item_description": "Lorem ipsum dolor sit, amet",
                    "item_stock": 201,
                    "item_color": "Blue",
                    "item_size": "Large"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "DATA NOT FOUND!",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": false,
                  "message": "DATA NOT FOUND!",
                  "status_code": 404,
                  "data": null
                }
              }
            }
          }
        }
      }
    },
    "/item/v1/:{id}": {
      "get": {
        "tags": [
          "items"
        ],
        "summary": "Find item by id",
        "description": "Finding an items using id",
        "operationId": "findPetsByTags",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Get Item Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": true,
                  "message": "Get Item Success",
                  "status_code": 201,
                  "data": {
                    "id": 16,
                    "item_name": "Motor Yamaha N-Max",
                    "item_price": 32000000,
                    "item_image": "https://www.yamaha-motor.co.id/uploads/products/new_product_model_image/202202151255313503V70891.png",
                    "item_description": "Lorem ipsum dolor sit, amet",
                    "item_stock": 201,
                    "item_color": "Blue",
                    "item_size": "Large"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "DATA NOT FOUND!",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": false,
                  "message": "DATA NOT FOUND!",
                  "status_code": 404,
                  "data": null
                }
              }
            }
          }
        }
      }
    },
    "/item/v1": {
      "get": {
        "tags": [
          "items"
        ],
        "summary": "get All Items",
        "description": "Retrieves all items",
        "operationId": "getAllItem",
        "responses": {
          "200": {
            "description": "Get item all success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": true,
                  "message": "Get Item Success",
                  "status_code": 201,
                  "data": {
                    "id": 16,
                    "item_name": "Motor Yamaha N-Max",
                    "item_price": 32000000,
                    "item_image": "https://www.yamaha-motor.co.id/uploads/products/new_product_model_image/202202151255313503V70891.png",
                    "item_description": "Lorem ipsum dolor sit, amet",
                    "item_stock": 201,
                    "item_color": "Blue",
                    "item_size": "Large"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/delete/item/v1/{id}": {
      "delete": {
        "tags": [
          "items"
        ],
        "summary": "delete item",
        "description": "delete ite by ID",
        "operationId": "deleteItem",
        "security": [
          {
            "JWTAuthorization": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID of the item to be deleted",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Delete Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": true,
                  "message": "Delete Success",
                  "status_code": 200,
                  "data": null
                }
              }
            }
          },
          "404": {
            "description": "ITEM NOT FOUND or ALREADY DELETED.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": false,
                  "message": "ITEM NOT FOUND or ALREADY DELETED.",
                  "status_code": 404,
                  "data": null
                }
              }
            }
          },
          "500": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/order/v1": {
      "post": {
        "tags": [
          "orders"
        ],
        "summary": "Add a new order",
        "description": "Add a new order to the store",
        "security": [
          {
            "JWTAuthorization": []
          }
        ],
        "requestBody": {
          "description": "Create a new order in the store",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/order"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Order created successfully",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": true,
                  "message": "Order created successfully",
                  "status_code": 201,
                  "data": {
                    "id": "e86c468d-380d-4123-b0db-2f998cce950e",
                    "user_id": 2,
                    "total_order_price": "66000000",
                    "status_order": "Pending",
                    "date_order_placed": "2024-03-07 13:15:34",
                    "date_order_paid": null,
                    "items": [
                      {
                        "item_name": "Motor Honda PCX",
                        "item_image": "https://gallery.poskota.co.id/storage/Foto/Foto_20230716_111017_nyD.jpeg",
                        "item_price": "30000000",
                        "order_items": null,
                        "quantity": 2,
                        "total_amount": "60000000"
                      }
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid input || Item Out Of Stock",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": false,
                  "message": "Please input a valid quantity! || Item Out Of Stock",
                  "status_code": 400,
                  "data": null
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Item Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": false,
                  "message": "Item Not Found",
                  "status_code": 404,
                  "data": null
                }
              }
            }
          }
        }
      }
    },
    "/update/order/v1": {
      "put": {
        "tags": [
          "orders"
        ],
        "summary": "Update Order",
        "description": "Update an Order",
        "operationId": "updatePet",
        "security": [
          {
            "JWTAuthorization": []
          }
        ],
        "requestBody": {
          "description": "Update an Order To Status Success",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "order_id": {
                    "type": "string",
                    "format": "uuid"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Order Update Success!",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": true,
                  "message": "Order Update Success!",
                  "status_code": 200,
                  "data": {
                    "id": "33ffd6ef-e88b-4089-bc9f-bb9226313099",
                    "user_id": 2,
                    "total_order_price": 60000000,
                    "status_order": "Success",
                    "date_order_placed": "2024-03-07 13:18:51",
                    "date_order_paid": "2024-03-07 14:9:51"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Admin Only To Access || Unauthorized"
          },
          "404": {
            "description": "Order not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": false,
                  "message": "Order Not Found!",
                  "status_code": 404,
                  "data": null
                }
              }
            }
          }
        }
      }
    },
    "/get/order/v1": {
      "get": {
        "tags": [
          "orders"
        ],
        "summary": "Finds Order by Id_Order",
        "description": "Finds Order by Id_Order",
        "parameters": [
          {
            "name": "id",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Get Order Successful",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": true,
                  "message": "Get Order Success!",
                  "status_code": 200,
                  "data": {
                    "id": "1f12c931-ca43-4dc1-89e0-95c8684968ab",
                    "user_id": 2,
                    "total_order_price": "35200000",
                    "status_order": "Success",
                    "date_order_placed": "2024-03-05 16:4:51",
                    "date_order_paid": "2024-03-05 16:18:55",
                    "items": [
                      {
                        "item_name": "Motor Yamaha N-Max",
                        "item_price": "32000000",
                        "item_image": "https://www.yamaha-motor.co.id/uploads/products/new_product_model_image/202202151255313503V70891.png",
                        "order_items": {
                          "quantity": 1,
                          "total_amount": "32000000"
                        }
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Order not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "example": {
                  "success": false,
                  "message": "Order Not Found!",
                  "status_code": 404,
                  "data": null
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "JWTAuthorization": {
        "type": "http",
        "scheme": "bearer"
      }
    },
    "schemas": {
      "updateUser": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "example": 8
          },
          "first_Name": {
            "type": "string",
            "example": "John"
          },
          "last_Name": {
            "type": "string",
            "example": "James"
          },
          "email": {
            "type": "string",
            "example": "john@email.com"
          },
          "password": {
            "type": "string",
            "example": "12345"
          },
          "phone": {
            "type": "string",
            "example": "0811910500222"
          }
        },
        "xml": {
          "name": "user"
        }
      },
      "users": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "format": "boolean",
            "example": true
          },
          "message": {
            "type": "string",
            "example": "Get All Data Success!"
          },
          "status_code": {
            "type": "integer",
            "example": 200
          },
          "data": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer",
                  "example": 1
                },
                "first_name": {
                  "type": "string",
                  "example": "Rama"
                },
                "last_name": {
                  "type": "string",
                  "description": "The last name of the user"
                },
                "email": {
                  "type": "string",
                  "example": "rariru@gmail.com"
                },
                "phone": {
                  "type": "string",
                  "example": "082213455123"
                },
                "created_at": {
                  "type": "string",
                  "example": "2024-01-20 19:42:12.811 +0700"
                },
                "updated_at": {
                  "type": "string",
                  "example": "2024-01-20 19:42:12.811 +0700"
                },
                "token_verify": {
                  "example": null
                },
                "verify": {
                  "type": "boolean",
                  "example": false
                },
                "user_detail": {
                  "example": null
                }
              }
            }
          }
        }
      },
      "findUsers": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "format": "boolean",
            "example": true
          },
          "message": {
            "type": "string",
            "example": "Get User Success"
          },
          "status_code": {
            "type": "integer",
            "example": 200
          },
          "data": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer",
                  "example": 1
                },
                "first_name": {
                  "type": "string",
                  "example": "Rama"
                },
                "last_name": {
                  "type": "string",
                  "description": "The last name of the user"
                },
                "email": {
                  "type": "string",
                  "example": "rariru@gmail.com"
                },
                "phone": {
                  "type": "string",
                  "example": "082213455123"
                },
                "created_at": {
                  "type": "string",
                  "example": "2024-01-20 19:42:12.811 +0700"
                },
                "updated_at": {
                  "type": "string",
                  "example": "2024-01-20 19:42:12.811 +0700"
                },
                "token_verify": {
                  "example": null
                },
                "verify": {
                  "type": "boolean",
                  "example": false
                },
                "user_detail": {
                  "example": null
                }
              }
            }
          }
        }
      },
      "userNotFound": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": false
          },
          "message": {
            "type": "string",
            "example": "User Not Found"
          },
          "status_code": {
            "type": "integer",
            "example": 404
          },
          "data": {
            "example": null
          }
        }
      },
      "userDetail": {
        "type": "object",
        "properties": {
          "address": {
            "type": "string",
            "example": "Merderka street"
          },
          "city": {
            "type": "string",
            "example": "Bandung city"
          },
          "postal_code": {
            "type": "string",
            "example": "40111"
          },
          "country_code": {
            "type": "string",
            "example": "Indonesia"
          }
        }
      },
      "registerUser": {
        "type": "object",
        "properties": {
          "first_Name": {
            "type": "string",
            "example": "John"
          },
          "last_Name": {
            "type": "string",
            "example": "James"
          },
          "email": {
            "type": "string",
            "example": "john@email.com"
          },
          "password": {
            "type": "string",
            "example": "12345"
          },
          "phone": {
            "type": "string",
            "example": "0811910500222"
          },
          "address": {
            "type": "string",
            "example": "Merderka street"
          },
          "city": {
            "type": "string",
            "example": "Bandung city"
          },
          "postal_code": {
            "type": "string",
            "example": "40111"
          },
          "country_code": {
            "type": "string",
            "example": "Indonesia"
          }
        }
      },
      "loginUser": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "example": "john@email.com"
          },
          "password": {
            "type": "string",
            "example": "12345"
          }
        }
      },
      "order": {
        "type": "object",
        "properties": {
          "item_id": {
            "type": "integer",
            "format": "int64",
            "example": 10
          },
          "quantity": {
            "type": "integer",
            "format": "int32",
            "example": 7
          }
        }
      },
      "Item": {
        "type": "object",
        "properties": {
          "item_name": {
            "type": "string",
            "example": "Motor Yamaha N-Max"
          },
          "item_image": {
            "type": "string",
            "example": "https://www.yamaha-motor.co.id/uploads/products/new_product_model_image/202202151255313503V70891.png"
          },
          "item_description": {
            "type": "string",
            "example": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto magnam ad quos provident impedit. Deserunt asperiores, nulla, in ipsa libero tenetur magnam eum harum nihil repudiandae, expedita doloribus inventore sed"
          },
          "item_stock": {
            "type": "integer",
            "example": 201
          },
          "item_price": {
            "type": "number",
            "format": "float",
            "example": 32000000
          }
        }
      },
      "updateItem": {
        "type": "object",
        "properties": {
          "item_name": {
            "type": "string",
            "example": "Motor Yamaha N-Max"
          },
          "item_price": {
            "type": "number",
            "format": "float",
            "example": 32000000
          },
          "item_image": {
            "type": "string",
            "example": "https://www.yamaha-motor.co.id/uploads/products/new_product_model_image/202202151255313503V70891.png"
          },
          "item_description": {
            "type": "string",
            "example": "Lorem ipsum dolor sit, amet"
          },
          "item_stock": {
            "type": "integer",
            "example": 201
          },
          "item_color": {
            "type": "string",
            "example": "Blue"
          },
          "item_size": {
            "type": "string",
            "example": "Large"
          }
        }
      },
      "ItemFormData": {
        "type": "object",
        "properties": {
          "item_name": {
            "type": "string"
          },
          "item_price": {
            "type": "string"
          },
          "item_description": {
            "type": "string"
          },
          "item_stock": {
            "type": "string"
          },
          "item_image": {
            "type": "string",
            "format": "binary"
          }
        }
      },
      "Response": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          },
          "status_code": {
            "type": "integer"
          },
          "data": {
            "type": "object"
          }
        }
      }
    }
  }
}
 